version: "3.9"

services:
  instagram-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram-media-api
    ports:
      - "8080:8080"
    environment:
      # Optional environment variables
      NODE_ENV: production
    restart: unless-stopped
